image: alpine:latest

variables:
  POSTGRES_ENABLED: "false"
  DOCKER_DRIVER: overlay2
  ROLLOUT_RESOURCE_TYPE: deployment
  DOCKER_TLS_CERTDIR: ""  # https://gitlab.com/gitlab-org/gitlab-runner/issues/4501

stages:
  - build
  - test
  - deploy

include:
  - local: /DevOps/Jobs/Build.gitlab-ci.yml
  - local: /DevOps/Jobs/Test.gitlab-ci.yml
  - local: /DevOps/Jobs/Deploy.gitlab-ci.yml
