code_quality:
  stage: test
  image: docker:stable
  allow_failure: true
  services:
    - docker:stable-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo 'Bell Soft Network DevOps Code Quality Stage'
    - |
      if ! docker info &>/dev/null; then
        if [ -z "$DOCKER_HOST" -a "$KUBERNETES_PORT" ]; then
          export DOCKER_HOST='tcp://localhost:2375'
        fi
      fi
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD/src/main/java":/code/src/main/java
        --volume "$PWD/src/main/resources/templates":/code/src/main/resources/templates
        --volume "$PWD/src/test/java":/code/src/test/java
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:12-0-stable" /code
  artifacts:
    paths: [gl-code-quality-report.json]
    reports:
      codequality: gl-code-quality-report.json
    expire_in: 1 week
  dependencies: []
  only:
    refs:
      - branches
      - tags
  only:
    refs:
      - master
      - dev_main
  except:
    variables:
      - $CODE_QUALITY_DISABLED
  retry: 2
