deploy:
  stage: deploy
  before_script:
    - chmod +x ./gradlew
  script:
    - echo "Start Build clean.."
    - ./gradlew clean
    - echo "Start Build BootJar.."
    - ./gradlew bootJar
    - echo "Start Server Deploy Process.."
    - cp ./build/libs/*.jar $SERVER_ROOT_PATH/bellsmarthome.jar
    - echo "Restart Server Service.."
    - systemctl --user restart bellsmarthome
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$DEPLOY_DISABLED'
      when: never
  tags:
    - deploy
