test:
  stage: test
  image: gliderlabs/herokuish:latest
  script:
    - echo 'Bell Soft Network DevOps Test Stage'
    - cp -R . /tmp/app
    - /bin/herokuish buildpack test
  rules:
    - if: '$TEST_DISABLED'
      when: never
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'
