# Test Coverage Parsing expression
# ([0-9]{1,3}.[0-9]*).%.covered
variables:
  JACOCO_CSV_LOCATION: '$CI_PROJECT_DIR/build/jacoco/csv'

test:
  stage: test
  image: gradle:6.6.1-jdk8
  needs: []
  script:
    - gradle test
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' $JACOCO_CSV_LOCATION
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
  rules:
    - if: '$TEST_DISABLED'
      when: never
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'