test:
  stage: test
  image: java:8
  needs: []
  script:
    - echo 'Bell Soft Network DevOps Gradle Test Stage'
    - sh gradlew test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
  rules:
    - if: '$TEST_DISABLED'
      when: never
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'