kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ${APPLICATION_NAME}
  namespace: ${APPLICATION_NAMESPACE}
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.org/websocket-services: "${APPLICATION_SERVICE_NAME}"
  labels:
    app: ${PROJECT_NAME}
    env: ${APPLICATION_ENVIRONMENT}
spec:
  tls:
    - hosts:
        - ${APPLICATION_URL}
      secretName: ${APPLICATION_TLS_SECRET_NAME}
  rules:
    - host: ${APPLICATION_URL}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${APPLICATION_SERVICE_NAME}
                port:
                  number: 8080
  ingressClassName: public
