include:
  - local: /.gitlab/ci/jobs/templates/gradle.gitlab-ci.yaml
  - local: /.gitlab/ci/jobs/templates/docker.gitlab-ci.yaml

.build:
  extends:
    - .gradle_cache
  stage: build
  rules:
    - if: "$TEST_DISABLED || $BUILD_DISABLED"
      when: never
    - if: "$CI_COMMIT_REF_PROTECTED"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && "$CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED"
    - if: "$CI_COMMIT_REF_NAME"
      when: manual

build_boot_image:
  extends:
    - .build
    - .in_docker
  variables:
    PROPERTY_REGISTRY: "-PproxyRegistryUrl=${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX} -PprojectRegistryUrl=${CI_REGISTRY_URL} -PregistryUser=${CI_REGISTRY_USER} -PregistryPassword=${CI_REGISTRY_PASSWORD} -PregistryEmail=${GITLAB_USER_EMAIL}"
    PROPERTY_BUILD: "-PbindingsDir=${CI_PROJECT_DIR}/bindings -PgradleDir=${CI_PROJECT_DIR}/.gradle-cache"
    PROPERTY_IMAGE: "-PimagePath=${CI_REGISTRY_IMAGE} -PimageBaseName=${CI_COMMIT_REF_SLUG} -PimageTag=${CI_COMMIT_SHA}"
    PROPERTY_DOCKER: "-PdockerHost=${DOCKER_HOST} -PisDockerTlsVerify=true -PdockerCertPath=${DOCKER_CERT_PATH}"
    # PROPERTY_BUILDER_IMAGE: "--builder ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/paketobuildpacks/builder:base"
  script:
    - gradle bootBuildImage ${GRADLE_CACHE_ARGS} --publishImage ${PROPERTY_REGISTRY} ${PROPERTY_BUILD} ${PROPERTY_IMAGE} ${PROPERTY_DOCKER}
